apiVersion: v1
kind: Pod
metadata:
  name: pod-test-nfs
spec:
  containers:
  - name: test-nfs
    image: alpine
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: "/mnt/nfs"
      name: nfs-volume
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: pvc-nfs-kubedata
