apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-kubedata
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/kubedata
    server: 10.0.0.6
  persistentVolumeReclaimPolicy: Retain

