apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-kubedata
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-nfs-kubedata
  storageClassName: ""
